# Generated by Django 4.1.1 on 2022-10-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('skill1', models.CharField(max_length=100)),
                ('skill2', models.CharField(max_length=100)),
                ('skill3', models.CharField(max_length=100)),
                ('skill4', models.CharField(max_length=100)),
                ('Experience1title', models.IntegerField()),
                ('Experience1dur', models.IntegerField()),
                ('Experiencedesc', models.IntegerField()),
                ('Experience2title', models.IntegerField()),
                ('Experience2dur', models.IntegerField()),
                ('Experience2desc', models.IntegerField()),
                ('Education1', models.CharField(max_length=100)),
                ('Education1dur', models.CharField(max_length=100)),
                ('Education1score', models.IntegerField()),
                ('Education2', models.CharField(max_length=100)),
                ('Education2dur', models.CharField(max_length=100)),
                ('Education2score', models.IntegerField()),
                ('Education3', models.CharField(max_length=100)),
                ('Education3dur', models.CharField(max_length=100)),
                ('Education3score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
